from fastapi import APIRouter
from fastapi.responses import FileResponse

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

router = APIRouter()


@router.post("/generate-report")
async def generate_report(
    payload: dict
):

    pdf_path = "WorkSphere_Report.pdf"

    doc = SimpleDocTemplate(
        pdf_path
    )

    styles = (
        getSampleStyleSheet()
    )

    report = payload["report"]

    content = []

    content.append(
        Paragraph(
            "WorkSphere AI Executive Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # Executive Summary

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            report.get(
                "executive_summary",
                ""
            ),
            styles["BodyText"]
        )
    )

    # Business Impact

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Business Impact",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            report.get(
                "business_impact",
                ""
            ),
            styles["BodyText"]
        )
    )

    # Priority Actions

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Priority Actions",
            styles["Heading2"]
        )
    )

    for action in report.get(
        "priority_actions",
        []
    ):

        content.append(
            Paragraph(
                f"• {action}",
                styles["BodyText"]
            )
        )

    # Risks

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Top Risks",
            styles["Heading2"]
        )
    )

    for risk in report.get(
        "top_risks",
        []
    ):

        content.append(
            Paragraph(
                f"• {risk}",
                styles["BodyText"]
            )
        )

    # Recommendations

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "AI Recommendations",
            styles["Heading2"]
        )
    )

    for item in report.get(
        "key_insights",
        []
    ):

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    # Knowledge Sources

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Knowledge Sources Used",
            styles["Heading2"]
        )
    )

    for doc_item in payload.get(
        "retrieval",
        []
    ):

        content.append(
            Paragraph(
                f"• {doc_item['document']}",
                styles["BodyText"]
            )
        )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by WorkSphere AI Multi-Agent Intelligence Platform",
            styles["Italic"]
        )
    )

    doc.build(
        content
    )

    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename="WorkSphere_Report.pdf"
    )